-- MySQL Script generated by MySQL Workbench
-- Пнд 09 Янв 2017 19:06:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Agregator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agregator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agregator` DEFAULT CHARACTER SET utf8 ;
USE `Agregator` ;

-- -----------------------------------------------------
-- Table `Agregator`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Articles` (
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `text` TEXT NULL,
  `article_create_datetime` DATETIME NULL,
  `link_to_article` TEXT NULL,
  PRIMARY KEY (`article_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agregator`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agregator`.`Articles_To_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Articles_To_Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_id` INT NULL,
  `tag_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agregator`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `user_create_date` DATE NULL,
  `user_last_login_datetime` DATETIME NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agregator`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `text` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `article_id` INT NULL,
  `comment_parrent_id` INT NULL,
  `comment_create_datetime` DATETIME NULL,
  PRIMARY KEY (`comment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agregator`.`Users_to_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Users_to_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `tag_id` INT NULL,
  `count_tag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
