-- MySQL Script generated by MySQL Workbench
-- Чтв 12 Янв 2017 22:52:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Agregator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agregator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agregator` DEFAULT CHARACTER SET utf8 ;
USE `Agregator` ;

-- -----------------------------------------------------
-- Table `Agregator`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NOT NULL,
  `synonyms` VARCHAR(255) NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Articles` (
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `text` TEXT NOT NULL,
  `article_create_datetime` DATETIME NOT NULL,
  `link_to_article` TEXT NOT NULL,
  `category_id` INT NOT NULL,
  `Article_JSON` JSON NOT NULL,
  `sourse` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`article_id`),
  INDEX `category_id_idx` (`category_id` ASC),
  UNIQUE INDEX `link_to_article_UNIQUE` (`link_to_article` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Articles_To_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Articles_To_Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `article_id_idx` (`article_id` ASC),
  INDEX `tag_id_idx` (`tag_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `user_create_date` DATE NOT NULL,
  `user_last_login_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  `comment_parrent_id` INT NOT NULL,
  `comment_create_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `article_id_idx` (`article_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Users_to_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Users_to_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `count_tag` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `tag_id_idx` (`tag_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`RSS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`RSS` (
  `rss_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `category_id` INT NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `sourse` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`rss_id`),
  UNIQUE INDEX `link_UNIQUE` (`link` ASC),
  INDEX `category_id_idx` (`category_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Sites` (
  `site_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  `method_of_parsing` ENUM('PhpQuery', 'cURL') NOT NULL,
  `parsing_settings` JSON NOT NULL,
  `make_parsing` TINYINT(1) NOT NULL,
  PRIMARY KEY (`site_id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Agregator`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agregator`.`Images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `link_to_image` VARCHAR(255) NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `article_id_idx` (`article_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
